name: "Build Android"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HEADSPIN_API_TOKEN: ${{ secrets.HEADSPIN_API_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: "gradle"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node  
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: NPM Install
        run: |
          npm install
      - name: Build application
        run: |
             cd ./android
             ./gradlew assembleDebug             
      - name: Upload application to HeadSpin
        run: |
          cp ./android/app/build/outputs/apk/debug/app-debug.apk ./TheApp.apk
          curl -X POST "https://$HEADSPIN_API_TOKEN@api-dev.headspin.io/v1/app/upload" -F app="@TheApp.apk"
