name: "Build iOS"

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - .gitignore
      - .editorconfig
      - .eslintrc.js
      - .node-version
      - .prettierrc.js
      - .ruby-version
      - android/**
      - .github/workflows/build-android.yml
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - .gitignore
      - .editorconfig
      - .eslintrc.js
      - .node-version
      - .prettierrc.js
      - .ruby-version
      - android/**
      - .github/workflows/build-android.yml

jobs:
  build:
    runs-on: macos-latest
    env:
      HEADSPIN_API_TOKEN: ${{ secrets.HEADSPIN_API_TOKEN }}
      WORKSPACE: ${{ 'TheApp.xcworkspace' }}
      SCHEME: ${{ 'TheApp' }}
      CONFIGURATION: ${{ 'Release' }}
      PROJECT_DIR: ${{ 'ios' }}
      DERIVED_DATA_DIR: ${{ 'DerivedData' }}
      PRODUCT_PATH: ${{ 'DerivedData/Build/Products/Release-iphoneos/TheApp.app' }}
      DESTINATION: ${{ 'generic/platform=iOS' }}
      CODE_SIGN_IDENTITY: ${{ secrets.CODE_SIGN_IDENTITY }}
      SIGNING_CERTIFICATE: ${{ secrets.SIGNING_CERTIFICATE }}
      SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
      PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
      PROVISIONING_PROFILE_UUID: ${{ secrets.PROVISIONING_PROFILE_UUID }}
      KEYCHAIN_PWD: ${{ secrets.KEYCHAIN_PWD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Keychain Setup
        run: |
          export CERT_PATH=$RUNNER_TEMP/dist_certificate.p12
          export PP_PATH=$RUNNER_TEMP/pp.mobileprovision
          export KCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n $SIGNING_CERTIFICATE | base64 -D > $CERT_PATH
          echo -n $PROVISIONING_PROFILE | base64 -D > $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PWD" $KCHAIN_PATH
          security set-keychain-settings -lut 21600 $KCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PWD" $KCHAIN_PATH

          # import certificate to keychain
          security import $CERT_PATH -P "$SIGNING_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KCHAIN_PATH
          security list-keychain -d user -s $KCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Xcode Version
        run: /usr/bin/xcodebuild -version

      - name: NPM Install
        run: npm install

      - name: Pod Install
        run: cd $PROJECT_DIR && pod install

      - name: Build App
        run: |
          export KCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          security unlock-keychain -p "$KEYCHAIN_PWD" $KCHAIN_PATH
          cd $PROJECT_DIR
          xcodebuild -workspace $WORKSPACE \
            -configuration $CONFIGURATION \
            -scheme $SCHEME \
            -destination $DESTINATION \
            -allowProvisioningUpdates \
            -derivedDataPath $DERIVED_DATA_DIR \
            OTHER_CODE_SIGN_FLAGS="--keychain=$KCHAIN_PATH" \
            PROVISIONING_STYLE="Manual" \
            PROVISIONING_PROFILE="$PROVISIONING_PROFILE_UUID" \
            CODE_SIGN_STYLE="Manual" \
            CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY"

      - name: Archive IPA
        run: |
          cd $PROJECT_DIR
          ls -la ./DerivedData
          ls -la ./DerivedData/Build
          ls -la ./DerivedData/Build/Products
          ls -la ./DerivedData/Build/Products/Release-iphoneos
          ls -la ./DerivedData/Build/Products/Release-iphoneos/TheApp.app
          rm -rf Payload
          mkdir Payload
          cp -R $PRODUCT_PATH Payload/
          zip -r TheApp.ipa Payload/

      - name: Upload to HeadSpin
        run: |
          export APP_ID=$(curl -X POST "https://$HEADSPIN_API_TOKEN@api-dev.headspin.io/v1/app/upload" -F app="@ios/TheApp.ipa" | jq -r .app_id)
          echo "APP_ID=$APP_ID" >> "$GITHUB_ENV"

      - name: Run Appium Tests
        run: |
          export HEADSPIN_APP_ID="${{ env.APP_ID }}"
          export GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          export BUILD_ID="$GITHUB_REF_NAME:$GIT_HASH"
          DEBUG=1 HEADSPIN=1 IOS=1 REAL_DEVICE=1 npm run test -- --parallel --jobs 3

      - name: Clean Up Keys
        if: ${{ always() }}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
          rm -rf ~/Library/MobileDevice/Provisioning\ Profiles/pp.mobileprovision
